config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :posts
  resources :categories, except: [:show]
  get "c/:url" => "categories#show", as: :show_category

  post "message/send" => "public#send_enguiry_to_user", as: :send_enquiry
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/faqs" => "public#faqs", as: :faqs 
  get "/scams" => "public#scams", as: :scams 
  get "/terms" => "public#terms", as: :terms 
  get "/safety" => "public#safety", as: :safety 

  root to: "public#home"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :parent, class_name: "Category", optional: true
    has_many :subcategories, class_name: "Category", foreign_key: :parent_id, dependent: :destroy
    has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category
    belongs_to :account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    category_ids = @category.subcategories.ids
    category_ids << @category.id
    @posts = Post.where(category_id: category_ids)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find_by_url(params[:url])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.fetch(:category, {})
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, except: [:show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.account_id = current_account.id if account_signed_in?

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.fetch(:post, {}).permit(:title, :content, :category_id)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController

    def home
        @categories = Category.where(parent_id: nil)
    end

    def send_enguiry_to_user
        @post = Post.find(params[:post_id])
        
        if @post.present? 
            ContactMailer.post_enquiry(@post.id, params[:email], params[:message]).deliver_now
            flash[:success] = "Message sent successfully"
        else
            flash[:danger] = "Unable to send message"
        end

        redirect_to post_path(@post)
    end

    def faqs
    end

    def scams
    end

    def safety
    end

    def terms
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def is_home?
        controller.controller_name == "public" && controller.action_name == "home"
    end

    def is_auth?
        controller.controller_name == "sessions" || controller.controller_name == "registrations"
    end

    def flash_notifications
        flash_messages = []

        flash.each do |type, message|
            type = 'success' if type == 'notice'
            type = 'error'   if type == 'alert' || type == 'danger'
            text = "toastr['#{type}']('#{message}'};"
            flash_messages << text.html_safe unless message.blank?
        end

        "<script>$(function(){ #{ flash_messages.join("\n") } });</script>".html_safe if flash_messages.any?
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/categories/_category_sidebar.html.erb
<p><strong><%= @category.name %></strong></p>

<ul>
    <% @category.subcategories.each do |subcategory| %>
        <li><%= link_to subcategory.name, show_category_path(subcategory.url) %></li>
    <% end %>
</ul>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% @posts.each do |post| %>
    <div class="category-post">
        <span class="post-date"><%= time_ago_in_words post.created_at %> ago</span>
        <span class="post-title"><%= link_to post.title, post_path(post) %></span> 
    </div>
<% end %>
<% if @posts.empty? %>
    <p>No posts to display.</p>
<% end %>

app/views/layouts/_breadcrumb_nav.html.erb
    <div class="row">
        <div class="col-12 pt-4 pb-3">
            <% if account_signed_in? %>
            <%= link_to "Sign out", destroy_account_session_path, method: :delete, class: "float-right text-dark ml-3" %>
            <% else %>
            <%= link_to "Sign In", new_account_session_path, class: "float-right text-dark ml-3" %>
            <%= link_to "New Account", new_account_registration_path, class: "float-right text-dark ml-3" %>
            <% end %>

            <%= link_to "Dashboard", "#", class: "float-right text-dark ml-3" if account_signed_in? %>

            <%= link_to "Home", root_path %> >>

            <% if @post.present? && !@post.new_record?
                category = @post.category
                parent = category.parent
            %>
            <% if parent.present? %>
                <%= link_to parent.name, show_category_path(parent.url) %> >>
            <% end %>
            <%= link_to category.name, show_category_path(category.url) %> >>
            <%= @post.title %>
            <% elsif @category.present? 
                parent = @category.parent
            %>
            <% if parent.present? %>
                <%= link_to parent.name, show_category_path(parent.url) %> >>
            <% end %>

            <%= @category.name %>
            <% end %>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CraigslistClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+SC&dispaly=swap" rel="stylesheet">
  </head>

  <body>

    <div class="container">
      <div class="row">
        <div class="col-3">
          <%= link_to root_path, class: "text-dark" do %>
            <%= image_tag("app-logo.png", width: "200px", class: "mt-4 mb-5") %>
          <% end %>

          <p><%= link_to "Create new post", new_post_path, class: "btn btn-success" unless is_auth? %></p>

          <%= render "categories/category_sidebar" if controller.controller_name == "categories" %>
          
          <% if is_home? || is_auth? %>
            <div class="nav-pages mt-5">
              <p><%= link_to "help, faqs, abuse, legal", faqs_path %></p>
              <p><%= link_to "avoid scams and fraud", scams_path %></p>
              <p><%= link_to "personal safety tips", safety_path %></p>
              <p><%= link_to "terms of use", terms_path %></p>
            </div>
          <% end %>

        </div>
        <div class="col-9">
          <header id="header">
            <%= render "layouts/breadcrumb_nav" %>
          </header>
          <%= yield %>
        </div>
      </div>
    </div>
    
    <%= flash_notifications %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= form_with(model: post, local: true) do |form| %>
      <% if post.errors.any? %>
        <div id="error_explanation">
          <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :content %>
        <%= form.text_area :content, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :category_id %><br />
        <%= form.select :category_id, Category.all.collect {|c| [ c.name, c.id ]}, {}, { class: "form-control" } %> 
      </div>

      <div class="form-group">
        <%= form.submit "Save Post", class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<a href="javascript:document.print()" class="btn btn-sm btn-secondary float-right">Print</a>

<span class="posted-at-top">Posted <%= time_ago_in_words @post.created_at %> ago</span>

<h1 class="mt-4 mb-4"><%= @post.title %></h1>

<%= simple_format @post.content %>

<%= link_to "Send message to user", "#", id: "show_contact_form", class: "btn btn-info" %>

<p class="post-meta mt-4">
    <span class= "post-id">Post id: <%= @post.id.to_s %></span> 
    <span class="posted-at">Posted <%= time_ago_in_words @post.created_at %> ago</span>
</p>

<div id="contact-form" class="bg-light p-3">
    <div class="row">
        <div class="col-sm-6">
            <%= form_tag send_enquiry_path do %>
                <% user_email = account_signed_in? ? current_account.email : nil %>
                <%= hidden_field_tag :post_id, @post.id %>
                <div class="form-group">
                    <%= label_tag :email %>
                    <%= text_field_tag :email, user_email, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= label_tag :message %>
                    <%= text_area_tag :message, nil, class: "form-control" %>
                </div>  
                <%= submit_tag "Send Message", class: "btn btn-success" %>
            <% end %>
        </div>
    </div>
</div>